import React, { FC } from "react";
import { Button, Text, View } from "react-native";
import { List } from "react-native-paper";
import { DatePickerModal } from "react-native-paper-dates";
// import { DateTime } from "luxon";

type Props = { plasticCollection: PlasticCollection; interactable: boolean };
export type PlasticCollectionDetailsProps = Props;

// TODO: This should come autogenerated from the backend!
export type PlasticCollection = {
  id: string;
  requesterId: string;
  recipientPartnerId: string;
  numberOfUnits: number;
  streetName: string;
  streetNumber: string;
  city: string;
  zipCode: string;
  companyName?: string;
  collectionStatus: "pending" | "scheduled" | "delivered" | "received";
};

const PlasticCollectionDetails: FC<Props> = ({
  plasticCollection,
  interactable,
}) => {
  const {
    companyName,
    streetName,
    streetNumber,
    zipCode,
    city,
    numberOfUnits,
    collectionStatus,
    /*
    requesterId,
    recipientPartnerId,
     */
  } = plasticCollection;

  const title = companyName || `${streetName} ${streetNumber}`;

  const schedule = () => {
    console.log("Not implemented");
    // TODO: Do the call to schedule the pick-up at the specified date!
  };

  // TODO: FIX LUXON!
  const [date, setDate] = React.useState<Date | undefined>(undefined);
  const [open, setOpen] = React.useState(false);

  const selectPickupDate = () => setOpen(true);

  const onDismissSingle = () => {
    setOpen(false);
  };

  const onConfirmSingle = (params: any) => {
    setOpen(false);
    setDate(params.date);
  };

  return (
    <List.Accordion title={title}>
      {companyName && <Text>{companyName}</Text>}
      <Text>
        {streetName} {streetNumber}
      </Text>
      <Text>
        {city} {zipCode}
      </Text>
      <Text>Antal enheder {numberOfUnits}</Text>
      {interactable && collectionStatus && (
        <View>
          <Text>Planlæg afhentning</Text>
          <Text>Afhentningsdato: {date ? date.toString() : "Ikke valgt"}</Text>
          <Button title="Vælg afhentningsdato" onPress={selectPickupDate} />
          <DatePickerModal
            mode="single"
            visible={open}
            onDismiss={onDismissSingle}
            date={date}
            onConfirm={onConfirmSingle}
          />
          <Button title="Planlæg" onPress={schedule} />
        </View>
      )}
      {/* TODO: Make a button to register schedule pick-up and another to register delivery */}
    </List.Accordion>
  );
};

export default PlasticCollectionDetails;
