import AsyncStorage from "@react-native-async-storage/async-storage";
import axios, { AxiosResponse } from "axios";
import * as React from "react";
import { ActivityIndicator, Button, StyleSheet, TextInput } from "react-native";
import { Snackbar } from "react-native-paper";
import axiosUtils from "../utils/axios";

import { View } from "./Themed";

// TODO: This should come from autogenerated typings from the backend
type AppRole = {
  displayName: string;
  id: string;
};

export default function UserInvitationForm() {
  const [accessToken, setAccessToken] = React.useState<string | undefined>();

  AsyncStorage.getItem("accessToken").then((localAccessToken) => {
    setAccessToken(localAccessToken || undefined);
  });

  const [isLoadingRoles, setIsLoadingRoles] = React.useState(false);
  const [isLoadingInvite, setIsLoadingInvite] = React.useState(false);

  const [showSuccessSnackbar, setShowSuccessSnackbar] = React.useState(false);
  const dismissSuccessSnackbar = () => {
    setShowSuccessSnackbar(false);
    // TODO: This should probably be somewhere else
    setEmailToInvite("");
  };

  const [availableAppRoles, setAvailableAppRoles] = React.useState<AppRole[]>(
    []
  );

  // Initially, fetch the available app roles
  React.useEffect(() => {
    if (accessToken) {
      setIsLoadingRoles(true);

      axios
        .get("/UserAppRoles", {
          params: {
            code: "oYx2YQIRFLv7fVYRd4aV9Rj/EyzQGwTepONvms8DBLJPquUIh9sDAw==",
          },
          ...axiosUtils.getSharedAxiosConfig(accessToken),
        })
        .then((response: AxiosResponse<AppRole[]>) => {
          setAvailableAppRoles(response.data);
        })
        .finally(() => setIsLoadingRoles(false));
    }
  }, [accessToken]);

  const [emailToInvite, setEmailToInvite] = React.useState("");

  // TODO: Extend this with regexp to verify the shape of the email
  const emailToInviteIsInvalid = () => {
    return emailToInvite === "";
  };

  return (
    <View style={styles.container}>
      {isLoadingInvite ? (
        <ActivityIndicator />
      ) : (
        <TextInput
          value={emailToInvite}
          onChangeText={setEmailToInvite}
          style={styles.textInput}
        />
      )}
      <View style={styles.buttonContainer}>
        {isLoadingRoles ? (
          <ActivityIndicator />
        ) : (
          availableAppRoles.map((availableAppRole: AppRole) => {
            const onPress = () => {
              if (accessToken) {
                axios
                  .post(
                    "/InviteExternalUser",
                    {
                      email: emailToInvite,
                      appRoleId: availableAppRole.id,
                    },
                    {
                      params: {
                        code:
                          "aWOynA5/NVsQKHbFKrMS5brpi5HtVZM3oaw4BEiIWDaHxAb0OdBi2Q==",
                      },
                      ...axiosUtils.getSharedAxiosConfig(accessToken),
                    }
                  )
                  .then(() => setShowSuccessSnackbar(true))
                  .finally(() => setIsLoadingInvite(false));

                setEmailToInvite("");
                setIsLoadingInvite(true);
              }
            };

            return (
              <View key={availableAppRole.id} style={styles.button}>
                <Button
                  title={availableAppRole.displayName}
                  onPress={onPress}
                  disabled={emailToInviteIsInvalid()}
                />
              </View>
            );
          })
        )}
      </View>
      <Snackbar
        visible={showSuccessSnackbar}
        onDismiss={dismissSuccessSnackbar}
        action={{
          label: "OK",
          onPress: dismissSuccessSnackbar,
        }}
      >
        Brugeren er inviteret til MyTrash
      </Snackbar>
    </View>
  );
}

const styles = StyleSheet.create({
  textInput: {
    height: 30,
    marginBottom: 10,
    width: "80%",
    textAlign: "center",
    backgroundColor: "lightgrey",
  },
  container: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  buttonContainer: {
    flexDirection: "row",
  },
  button: {
    margin: 5,
  },
});
