import axios from "axios";
import React, { useState } from "react";
import { ActivityIndicator, Button, StyleSheet, TextInput } from "react-native";
import axiosUtils from "../utils/axios";

import { View } from "./Themed";
import DismissableSnackbar from "./shared/DismissableSnackbar";
import RoleSelector from "./RoleSelector";
import useAccessToken from "../hooks/useAccessToken";

// TODO: This should come from autogenerated typings from the backend

export default function UserInvitationForm() {
  const [rolesToInviteTo, setRolesToInviteTo] = useState<string[]>([]);
  const [isLoadingInvite, setIsLoadingInvite] = useState(false);

  const onDismiss = () => {
    setEmailToInvite("");
  };

  const [emailToInvite, setEmailToInvite] = useState("");
  const [showSnackbar, setShowSnackbar] = useState(false);

  // TODO: Extend this with regexp to verify the shape of the email
  const emailToInviteIsInvalid = () => {
    return emailToInvite === "";
  };

  const accessToken = useAccessToken();
  const inviteUser = () => {
    if (accessToken) {
      axios
        .post(
          "/InviteExternalUser",
          {
            email: emailToInvite,
            appRoleIds: rolesToInviteTo,
          },
          {
            params: {
              code: "aWOynA5/NVsQKHbFKrMS5brpi5HtVZM3oaw4BEiIWDaHxAb0OdBi2Q==",
            },
            ...axiosUtils.getSharedAxiosConfig(accessToken),
            // ..axiosUtils.getSharedAxiosConfig(accessToken),
          }
        )
        .then(() => setShowSnackbar(true))
        .finally(() => setIsLoadingInvite(false));

      setEmailToInvite("");
      setIsLoadingInvite(true);
    }
  };

  return (
    <View style={styles.container}>
      {isLoadingInvite ? (
        <ActivityIndicator />
      ) : (
        <View>
          <TextInput
            value={emailToInvite}
            onChangeText={setEmailToInvite}
            style={styles.textInput}
          />
          <RoleSelector
            selectionDisabled={emailToInviteIsInvalid()}
            roleSelectionState={[rolesToInviteTo, setRolesToInviteTo]}
          />
        </View>
      )}
      <Button onPress={inviteUser} title="Invite user" />
      <DismissableSnackbar
        title="Brugeren er blevet inviteret"
        showState={[showSnackbar, setShowSnackbar]}
        onDismiss={onDismiss}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  textInput: {
    height: 30,
    marginBottom: 10,
    width: "80%",
    textAlign: "center",
    backgroundColor: "lightgrey",
  },
  container: {
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  buttonContainer: {
    flexDirection: "row",
  },
  button: {
    margin: 5,
  },
});
