import React, { FC, useState } from "react";
import { Text, TouchableOpacity } from "react-native";
import { Badge, Card, List, useTheme } from "react-native-paper";
import InformationText from "../styled/InformationText";
import Subheader from "../styled/Subheader";

type PlasticCollectionDetailProps = {
  plasticCollection: PlasticCollection;
  hideWeight?: boolean;
};

// TODO: This should come autogenerated from the backend!
export type PlasticCollection = {
  id: string;
  clusterId: string;
  requesterId: string;
  recipientPartnerId: string;
  numberOfUnits: number;
  streetName: string;
  streetNumber: string;
  city: string;
  zipCode: string;
  isFirstCollection: boolean;
  isLastCollection: boolean;
  companyName?: string;
  comment?: string;
  scheduledPickupDate?: string;
  weight?: number;
  collectionStatus: "pending" | "scheduled" | "delivered" | "received";
};

// TODO: Unify this with BatchDetail!!
const PlasticCollectionDetail: FC<PlasticCollectionDetailProps> = ({
  plasticCollection,
  hideWeight = false,
  children,
}) => {
  const {
    companyName,
    streetName,
    streetNumber,
    zipCode,
    city,
    numberOfUnits,
    comment,
    weight,
  } = plasticCollection;
  const [showDetails, setShowDetails] = useState(false);
  const toggleDetails = () => setShowDetails(!showDetails);

  const { colors } = useTheme();

  const title = companyName || `${streetName} ${streetNumber}`;

  return (
    <Card style={styles.card}>
      <TouchableOpacity onPress={toggleDetails}>
        <Card.Title title={title} />
      </TouchableOpacity>
      {showDetails && (
        <Card.Content style={styles.cardContent}>
          {companyName && <InformationText>{companyName}</InformationText>}
          <InformationText>
            {streetName} {streetNumber}
          </InformationText>
          <InformationText>
            {city} {zipCode}
          </InformationText>
          {comment && <InformationText>{comment}</InformationText>}
          {weight && !hideWeight && (
            <InformationText>Vægt: {weight}kg</InformationText>
          )}
          <Text>
            Antal enheder{" "}
            <Badge
              visible
              style={{ backgroundColor: colors.primary }}
              size={30}
            >
              {numberOfUnits}
            </Badge>
          </Text>
          {children}
        </Card.Content>
      )}
      {/* TODO: Make a button to register schedule pick-up and another to register delivery */}
    </Card>
  );
};

type Props = {
  plasticCollections: PlasticCollection[];
  title: string;
  hideWeight?: boolean;
  children?: (plasticCollection: PlasticCollection) => React.ReactNode;
};

const PlasticCollectionsDetails: FC<Props> = ({
  plasticCollections,
  title,
  hideWeight = false,
  children,
}) => {
  return (
    <List.Section>
      <Subheader>{title}</Subheader>
      {plasticCollections.map((collection) => (
        <PlasticCollectionDetail
          key={collection.id}
          plasticCollection={collection}
          hideWeight={hideWeight}
        >
          {children && children(collection)}
        </PlasticCollectionDetail>
      ))}
    </List.Section>
  );
};

const styles = {
  card: {
    marginBottom: 15,
  },
  cardContent: {
    borderWidth: 0.3,
    padding: 15,
    margin: 15,
    borderColor: "lightgrey",
    borderStyle: "solid" as "solid",
  },
};

export default PlasticCollectionsDetails;
