import { AuthenticationProvider } from "@microsoft/microsoft-graph-client";
import { DefaultAzureCredential } from "@azure/identity";

class CustomAuthenticationProvider implements AuthenticationProvider {
  private azureCredential: DefaultAzureCredential;

  constructor() {
    this.azureCredential = new DefaultAzureCredential();
  }

  getAccessToken = async () => {
    return "eyJ0eXAiOiJKV1QiLCJub25jZSI6InFRTkY1QkRUQWpfb21acUItVkhUQVdDcm90a2VHOW92ejVlRDJvampsVFkiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMTJjYTk5NGYtZDk4Ny00MmUxLThlZjItMjdmOWM5MjJkMTQ1LyIsImlhdCI6MTYyMDc1Nzk0NCwibmJmIjoxNjIwNzU3OTQ0LCJleHAiOjE2MjA3NjE4NDQsImFjY3QiOjAsImFjciI6IjEiLCJhY3JzIjpbInVybjp1c2VyOnJlZ2lzdGVyc2VjdXJpdHlpbmZvIiwidXJuOm1pY3Jvc29mdDpyZXExIiwidXJuOm1pY3Jvc29mdDpyZXEyIiwidXJuOm1pY3Jvc29mdDpyZXEzIiwiYzEiLCJjMiIsImMzIiwiYzQiLCJjNSIsImM2IiwiYzciLCJjOCIsImM5IiwiYzEwIiwiYzExIiwiYzEyIiwiYzEzIiwiYzE0IiwiYzE1IiwiYzE2IiwiYzE3IiwiYzE4IiwiYzE5IiwiYzIwIiwiYzIxIiwiYzIyIiwiYzIzIiwiYzI0IiwiYzI1Il0sImFpbyI6IkFWUUFxLzhUQUFBQVgzWnY2bCtwZngwVEV4eEhoWEVjaWpjZy9IQXg5Q0lrQVovMXN4OHpjVDFrRmpyQWxNbGFKVGlKVTdVVU9vRDZCMkdIRXlhcGE3NXc2dUdLV3gxb1N2ZFVIL0kxcUI5VmVlMGpjejVqdUk0PSIsImFsdHNlY2lkIjoiMTpsaXZlLmNvbTowMDAzMDAwMEQwNzNENzE4IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJNaWNyb3NvZnQgQXp1cmUgQ0xJIiwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJlbWFpbCI6Im5pa2xhcy5ub2VycmVnYWFyZEBnbWFpbC5jb20iLCJmYW1pbHlfbmFtZSI6Ik1vc3MiLCJnaXZlbl9uYW1lIjoiTmlrbGFzIiwiaWRwIjoibGl2ZS5jb20iLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyMTMuMzIuMjQyLjIwNyIsIm5hbWUiOiJOaWtsYXMgTW9zcyIsIm9pZCI6ImY0NGRlNWE1LWVmOTQtNGU1MC1iMjMyLTM5NzcwZWYzNWFiZiIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzMjAwMTM5NjdGMkI3IiwicmgiOiIwLkFTSUFUNW5LRW9mWjRVS084aWY1eVNMUlJaVjNzQVRialJwR3UtNEMtZUdfZTBZeUFGby4iLCJzY3AiOiJBdWRpdExvZy5SZWFkLkFsbCBEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIFVzZXIuUmVhZFdyaXRlLkFsbCIsInN1YiI6Ik1sWnRMM0RmcjJDdkkzX2VHOTZkMWRTeGdCUUJuRG52amZBNFl1RERlUmsiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiIxMmNhOTk0Zi1kOTg3LTQyZTEtOGVmMi0yN2Y5YzkyMmQxNDUiLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI25pa2xhcy5ub2VycmVnYWFyZEBnbWFpbC5jb20iLCJ1dGkiOiJnckN3Z2MyVkEwbTk4WkdnQ3BsLUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyI2MmU5MDM5NC02OWY1LTQyMzctOTE5MC0wMTIxNzcxNDVlMTAiLCJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3RjZHQiOjE2MTk4ODc3MTB9.E60rNMm9fPC-tgCiK2vIuNO7rolFFSGBTSbs6iCnYhyjWCY0cVTjSzSiR7tub4q1RyTaOM-lNizEqfjc5PMQbTfu85-AnHpw1mUZBk8b_D2h7aLlFKlfmkh2D3QGPGFmF-nmyZB20xxKKop2mbLtcdFVuL2FLkGyJrsAndOFZF_ooWPMUkhRC4V70eo_dVaOZgKPCyrrgr8h70KwrvJUrTVjNnbaDCl1fc_Exq1y-jGeBoyzqGjm8SnQmKQMIULQQPAHmOUt-iSfSuni0qWcDd_2udG33nDcYkRfiAtDr93t1nMvv6L7xAdOMm-ehZRZ7S99Xx7Y0Ihub-9JRpBBOg";
    /*
    const accessToken = await this.azureCredential.getToken([
      "User.ReadWrite.All",
    ]);

    return accessToken.token;
    */
  };
}

export default CustomAuthenticationProvider;
