import { AuthenticationProvider } from "@microsoft/microsoft-graph-client";
import { DefaultAzureCredential } from "@azure/identity";

class CustomAuthenticationProvider implements AuthenticationProvider {
  private azureCredential: DefaultAzureCredential;

  constructor() {
    this.azureCredential = new DefaultAzureCredential();
  }

  getAccessToken = async () => {
    return "eyJ0eXAiOiJKV1QiLCJub25jZSI6IllzNHlqRk4tdDNqeXVVQU9RZEJkVk5kNjUycmx5Rm5GT2phZjhrVDRxOVUiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMTJjYTk5NGYtZDk4Ny00MmUxLThlZjItMjdmOWM5MjJkMTQ1LyIsImlhdCI6MTYyMDc2MzEwOCwibmJmIjoxNjIwNzYzMTA4LCJleHAiOjE2MjA3NjcwMDgsImFjY3QiOjAsImFjciI6IjEiLCJhY3JzIjpbInVybjp1c2VyOnJlZ2lzdGVyc2VjdXJpdHlpbmZvIiwidXJuOm1pY3Jvc29mdDpyZXExIiwidXJuOm1pY3Jvc29mdDpyZXEyIiwidXJuOm1pY3Jvc29mdDpyZXEzIiwiYzEiLCJjMiIsImMzIiwiYzQiLCJjNSIsImM2IiwiYzciLCJjOCIsImM5IiwiYzEwIiwiYzExIiwiYzEyIiwiYzEzIiwiYzE0IiwiYzE1IiwiYzE2IiwiYzE3IiwiYzE4IiwiYzE5IiwiYzIwIiwiYzIxIiwiYzIyIiwiYzIzIiwiYzI0IiwiYzI1Il0sImFpbyI6IkFWUUFxLzhUQUFBQUVaY2U0NVB2R1M1TnB5OXRTbDZwaXJFOHJyeURmbHBibkpCYzdnZllxRmhWTXY5NzBKZXc1dFlyTFphOGRmUUh6UjBsRDkvSk1ubU9XUVpiN2x0UEpHdlphMzNvQy96MU8xUjY0ak1CNnVVPSIsImFsdHNlY2lkIjoiMTpsaXZlLmNvbTowMDAzMDAwMEQwNzNENzE4IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJNaWNyb3NvZnQgQXp1cmUgQ0xJIiwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJlbWFpbCI6Im5pa2xhcy5ub2VycmVnYWFyZEBnbWFpbC5jb20iLCJmYW1pbHlfbmFtZSI6Ik1vc3MiLCJnaXZlbl9uYW1lIjoiTmlrbGFzIiwiaWRwIjoibGl2ZS5jb20iLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyMTMuMzIuMjQyLjIwNyIsIm5hbWUiOiJOaWtsYXMgTW9zcyIsIm9pZCI6ImY0NGRlNWE1LWVmOTQtNGU1MC1iMjMyLTM5NzcwZWYzNWFiZiIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzMjAwMTM5NjdGMkI3IiwicmgiOiIwLkFTSUFUNW5LRW9mWjRVS084aWY1eVNMUlJaVjNzQVRialJwR3UtNEMtZUdfZTBZeUFGby4iLCJzY3AiOiJBdWRpdExvZy5SZWFkLkFsbCBEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBHcm91cC5SZWFkV3JpdGUuQWxsIFVzZXIuUmVhZFdyaXRlLkFsbCIsInN1YiI6Ik1sWnRMM0RmcjJDdkkzX2VHOTZkMWRTeGdCUUJuRG52amZBNFl1RERlUmsiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiIxMmNhOTk0Zi1kOTg3LTQyZTEtOGVmMi0yN2Y5YzkyMmQxNDUiLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI25pa2xhcy5ub2VycmVnYWFyZEBnbWFpbC5jb20iLCJ1dGkiOiJ5LTNtQ0JvUmpVNks4N00wSWoyQkFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyI2MmU5MDM5NC02OWY1LTQyMzctOTE5MC0wMTIxNzcxNDVlMTAiLCJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3RjZHQiOjE2MTk4ODc3MTB9.JUy_soLwYIB3uZq4-u-sUTUQcbeLB86gEiLvVs9q9kOeKm8eBpTtADYy-OXduC-6QlOtbiz91JTH22z8dp0m4Z7LqASz717RgNBkAzvCUFwn_XwKEb-raVpKG_G53SYxRp430AVph10NKnUMKfg7KdZElM1vuxuECBKHrnbcSQDkyvkTPvBDnFC0_1kONfs-ZYWPBp5AGEQJrqznvjs4FPBGtyb1kYwGEQmCjlPXejGaDCbpXiDYBfDuz8PbAwXwCh4ITly5clkWB5amRUsRepAIjNpgMHgA4uNxmK9RWwji-PYq6rujCX0Gn0gCusM1x1I2RTvOvRPl_NsjJKzuHQ";
    /*
    const accessToken = await this.azureCredential.getToken([
      "User.ReadWrite.All",
    ]);

    return accessToken.token;
    */
  };
}

export default CustomAuthenticationProvider;
