import { StackScreenProps } from "@react-navigation/stack";
import axios from "axios";
import React, { FC, useEffect, useState } from "react";
import { StyleSheet } from "react-native";
import axiosUtils from "../utils/axios";

import { Text, View } from "../components/Themed";
import useAccessToken from "../hooks/useAccessToken";
import { TabsParamList } from "../typings/types";

type Props = StackScreenProps<TabsParamList, "Logistik">;

// TODO: This should come autogenerated from the backend!
type PlasticCollection = {
  id: string;
  requesterId: string;
  recipientPartnerId: string;
  numberOfUnits: number;
  streetName: string;
  streetNumber: string;
  city: string;
  zipCode: string;
  companyName?: string;
};

const LogisticsScreen: FC<Props> = ({ route }) => {
  const { userId } = route.params;
  const [plasticCollections, setPlasticCollections] = useState<
    PlasticCollection[]
  >([]);
  const accessToken = useAccessToken();

  useEffect(() => {
    axios
      .get("/GetPlasticCollections/", {
        params: { logisticsPartnerId: userId },
        ...axiosUtils.getSharedAxiosConfig(accessToken),
      })
      .then((axiosResult) => {
        const { data } = axiosResult;
        setPlasticCollections(data);
      });
  }, [accessToken, userId]);
  /* Vis afhentningsanmodninger */
  return (
    <View style={styles.container}>
      {plasticCollections.map((plasticCollection) => (
        <Text key={plasticCollection.id}>
          {plasticCollection.streetName} {plasticCollection.streetNumber}
        </Text>
      ))}
    </View>
  );
};

export default LogisticsScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "grey",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
  },
  separator: {
    marginVertical: 30,
    height: 1,
    width: "80%",
  },
});
