# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - houe-plastic-recycling-frontend(Production), Build and deploy React app

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_PACKAGE_PATH: './Frontend' # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_BUILD_PATH: './Frontend/web-build' # set this to the path to the build folder of your webapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: npm install, build, and test
      run: |
        pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        npm install

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: houe-plastic-recycling-frontend
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A5A334E7235F45A4823590912FD0572D }}
        package: ${{ env.AZURE_WEBAPP_BUILD_PATH }}

